import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const workspaceRoot = fileURLToPath(new URL("../..", import.meta.url));
const generatedPages = ["core", "layouts", "animations", "preview", "plugins", "shared"] as const;

const readWorkspaceFile = (filePath: string): Promise<string> =>
  readFile(path.join(workspaceRoot, filePath), "utf8");

describe("API documentation", () => {
  it("exposes the API documentation generator and overview pages", async () => {
    const packageJson = await readWorkspaceFile("package.json");
    const apiIndex = await readWorkspaceFile("docs/api/index.md");
    const configuration = await readWorkspaceFile("docs/api/configuration.md");
    const examples = await readWorkspaceFile("docs/api/examples.md");

    expect(packageJson).toContain('"docs:api": "node scripts/generate-api-docs.mjs"');
    expect(apiIndex).toContain("Generated Type Reference");
    expect(apiIndex).toContain("default exports are not part of the public contract");
    expect(configuration).toContain("ConfigManager");
    expect(configuration).toContain("Runtime Updates");
    expect(examples).toContain("Typed EventBus");
    expect(examples).toContain("Plugin Installation");
  });

  it("generates package API reference pages from public entrypoints", async () => {
    const generatedIndex = await readWorkspaceFile("docs/api/generated/index.md");

    expect(generatedIndex).toContain("Generated API Reference");

    for (const page of generatedPages) {
      const content = await readWorkspaceFile(`docs/api/generated/${page}.md`);

      expect(content).toContain("This file is generated by `pnpm docs:api`");
      expect(content).toContain("## Export Summary");
      expect(content).toContain("## Signatures");
    }

    const coreApi = await readWorkspaceFile("docs/api/generated/core.md");
    const previewApi = await readWorkspaceFile("docs/api/generated/preview.md");
    const pluginsApi = await readWorkspaceFile("docs/api/generated/plugins.md");

    expect(coreApi).toContain("`Gallery`");
    expect(coreApi).toContain("`EventBus`");
    expect(previewApi).toContain("`PreviewEngine`");
    expect(pluginsApi).toContain("`WatermarkPlugin`");
  });
});
